/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package competition.tournoigui;

import competition.Federation;
import data.FederationDB;
import java.awt.Button;
import java.awt.GridLayout;

/**
 *
 * @author Administrator
 */
public class FederationGUI extends javax.swing.JFrame {

    /**
     * Creates new form Federation
     */
    Federation f = new Federation("basket");
    FederationDB fedb= new FederationDB("federation.tmp");
    GridLayout layout = new GridLayout(1,1);
    JoueursGui joueursg = new JoueursGui();
    Inscription inscription = new Inscription();
    TournoiGUI tournoigui = new TournoiGUI();
    Dashboard dashboard = new Dashboard();
    public FederationGUI() {
        initComponents();
        ecran.setLayout(layout);
        ecran.removeAll();
        ecran.add(dashboard,new GridLayout(1, 1));
        dashboard.setVisible(true);
        if(fedb.all().size()<1) {
            fedb.ajouter(f);
        } else {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ecran = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        option = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        inscrire = new javax.swing.JMenuItem();
        joueurs = new javax.swing.JMenuItem();
        tournoi = new javax.swing.JMenu();
        resultour = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 450));
        setResizable(false);

        javax.swing.GroupLayout ecranLayout = new javax.swing.GroupLayout(ecran);
        ecran.setLayout(ecranLayout);
        ecranLayout.setHorizontalGroup(
            ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        ecranLayout.setVerticalGroup(
            ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        option.setText("option");

        jMenu5.setText("joueur");

        inscrire.setText("inscrire");
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });
        jMenu5.add(inscrire);

        joueurs.setText("liste des joueurs");
        joueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joueursActionPerformed(evt);
            }
        });
        jMenu5.add(joueurs);

        option.add(jMenu5);

        jMenuBar1.add(option);

        tournoi.setText("tournoi");
        tournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournoiActionPerformed(evt);
            }
        });

        resultour.setText("resultat du tournoi");
        resultour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultourActionPerformed(evt);
            }
        });
        tournoi.add(resultour);

        jMenuBar1.add(tournoi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ecran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ecran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
        tournoigui.setVisible(false);
        joueursg.setVisible(false);
        dashboard.setVisible(false);
        ecran.removeAll();
        ecran.add(inscription,new GridLayout(1, 1));
        inscription.setVisible(true);
    }//GEN-LAST:event_inscrireActionPerformed

    private void joueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joueursActionPerformed
        inscription.setVisible(false);
        tournoigui.setVisible(false);
        dashboard.setVisible(false);
        ecran.removeAll();
        ecran.add(joueursg,new GridLayout(1, 1));
        joueursg.fillTable();
        joueursg.setVisible(true);
        
    }//GEN-LAST:event_joueursActionPerformed

    private void tournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournoiActionPerformed
        
    }//GEN-LAST:event_tournoiActionPerformed

    private void resultourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultourActionPerformed
        inscription.setVisible(false);
        joueursg.setVisible(false);
        dashboard.setVisible(false);
        ecran.removeAll();
        ecran.add(tournoigui,new GridLayout(1, 1));
        tournoigui.setVisible(true);
    }//GEN-LAST:event_resultourActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FederationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FederationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FederationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FederationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FederationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ecran;
    private javax.swing.JMenuItem inscrire;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem joueurs;
    private javax.swing.JMenu option;
    private javax.swing.JMenuItem resultour;
    private javax.swing.JMenu tournoi;
    // End of variables declaration//GEN-END:variables
}
