/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package competition.tournoigui;

import competition.Federation;
import competition.Joueur;
import data.DBJoueur;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JoueursGui extends javax.swing.JPanel {
    private DBJoueur dbinstence = new DBJoueur("joueurs.tmp");
    private DefaultTableModel model;
    private Joueur selectedJoueur;
    private int row=0;
    
    /** Creates new form JoueursGui */
    public JoueursGui() {
        initComponents();
        fillTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ljoueurs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        actualiser = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        ljoueurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LICENCE", "NOM", "PRENOM", "points"
            }
        ));
        ljoueurs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ljoueurs.setGridColor(new java.awt.Color(0, 204, 51));
        ljoueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ljoueursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ljoueurs);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTES DES LICENCIES");

        actualiser.setText("actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        supprimer.setText("supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actualiser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supprimer)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(actualiser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        fillTable();
    }//GEN-LAST:event_actualiserActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        System.out.println(getSelectedJoueur());
        supprimer(getSelectedJoueur());
        suppMode();
        JOptionPane.showMessageDialog(this, "Suppression effective");
    }//GEN-LAST:event_supprimerActionPerformed

    private void ljoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ljoueursMouseClicked
        suppMode();
    }//GEN-LAST:event_ljoueursMouseClicked
    private void suppMode(){
        if(model!=null && model.getRowCount()==0){
            supprimer.setEnabled(false);
        }else{
            supprimer.setEnabled(true);
        }
    }
    public void fillTable(){
        suppMode();
        model= (DefaultTableModel) ljoueurs.getModel();
        for(int i=0;i<model.getRowCount();){
            model.removeRow(i);
        }
        for(Joueur personne:dbinstence.all()){
            model.addRow(personne.toObject());
        }
    }
    private void supprimer(Joueur joueur){
        if(dbinstence.getJoueur(joueur, -1)!=null){
            System.out.println("egaux");
        }else{
            System.out.println("Pas egaux");
        }
        model.removeRow(row);
    }
    private Joueur getSelectedJoueur(){
        selectedJoueur= new Joueur();
        row = ljoueurs.getSelectedRow();
        try{
        selectedJoueur.setNom(ljoueurs.getValueAt(row, 1).toString());
        selectedJoueur.setPrenom(ljoueurs.getValueAt(row, 2).toString());
        selectedJoueur.setNumLicence(ljoueurs.getValueAt(row, 0).toString());
        }catch(Exception e){
            
        }
        return selectedJoueur;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ljoueurs;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables

}
