/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package competition.tournoigui;
import competition.Federation;
import competition.Joueur;
import competition.Match;
import competition.Tournoi;
import competition.TournoiNonFiniException;
import data.DBJoueur;
import data.MatchDB;
import java.awt.Button;
import java.awt.GridLayout;
import java.awt.Label;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Administrator
 */
public class TournoiGUI extends javax.swing.JPanel {

    /**
     * Creates new form Tourn
     */
    Tournoi t;
    boolean state;
    Federation federation = new Federation();
    List<Joueur> listjoueurs;
    private DBJoueur dbinstence = new DBJoueur("joueurs.tmp");
    public TournoiGUI() {
        listjoueurs=dbinstence.all();
        initComponents();
        t = new Tournoi(listjoueurs);
        federation.setLicence(listjoueurs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabul = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        voir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        gagnant = new javax.swing.JLabel();
        perdant = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        option = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jouer = new javax.swing.JButton();
        inidata = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        attrpoint = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        infoattp = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        voir.setText("voir");
        voir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirActionPerformed(evt);
            }
        });
        jPanel4.add(voir);

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        gagnant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gagnant.setText("qui est Gagnant ?");

        perdant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        perdant.setText("qui est Perdant ?");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Resultats pour le tournoi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gagnant, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(perdant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gagnant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(perdant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);

        tabul.addTab("resultat", jPanel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jouer.setText("jouer");
        jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerActionPerformed(evt);
            }
        });
        jPanel5.add(jouer);

        inidata.setText("INITIALISER LES DONNEES");
        inidata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inidataActionPerformed(evt);
            }
        });
        jPanel5.add(inidata);

        jButton4.setText("initialiser le tournoi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        attrpoint.setText("ATTRIBUER POINTS");
        attrpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrpointActionPerformed(evt);
            }
        });
        jPanel5.add(attrpoint);

        jPanel6.setBackground(new java.awt.Color(0, 102, 0));
        jPanel6.setLayout(new java.awt.GridLayout());

        infoattp.setBackground(new java.awt.Color(255, 153, 0));
        infoattp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        infoattp.setText("---------Patientez SVP-------Les points Attribue Vous sera donne--------");
        infoattp.setOpaque(true);
        jPanel6.add(infoattp);

        javax.swing.GroupLayout optionLayout = new javax.swing.GroupLayout(option);
        option.setLayout(optionLayout);
        optionLayout.setHorizontalGroup(
            optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        optionLayout.setVerticalGroup(
            optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabul.addTab("option", option);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabul)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabul)
                .addContainerGap())
        );

        tabul.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerActionPerformed
        if(dbinstence.all().size()<4){
            JOptionPane.showMessageDialog(this, "Veuillez Avoir au moins 4 Licencies");
            return;
        }
        if(t.getTour()!=null && !t.tourExist()){
            t = new Tournoi(dbinstence.all());
        }
        try {
            t.joueUnTour();
        } catch (TournoiNonFiniException ex) {
            Logger.getLogger(TournoiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(t!=null && t.isFini()){
            try {
                JOptionPane.showMessageDialog(this, "Le Tournoi est fini et gnagne par nom: \n"+t.getVainqueur().getNom()+"\nPrenom: "+t.getVainqueur().getPrenom()+"\nnombre de points: "+t.getVainqueur().getPoints());
            } catch (TournoiNonFiniException ex) {
                Logger.getLogger(TournoiGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        DefaultTableModel model = new DefaultTableModel();
        JTable tabl = new JTable();
        Vector vector1  = new Vector();
        Vector vector2  = new Vector();
        int c=0;
//        MatchDB matchdb = new MatchDB("matchs.tmp");
        if(t.getTour()!=null){
            for(Match m:t.getTour()){
//            matchdb.ajouter(m);
                c+=1;
                Joueur j1 = m.getJoueur1();
                Joueur j2 = m.getJoueur2();
                model.addColumn("match",new Object[]{"MATCH "+c});
                vector1.add(j1.getNom()+" "+j1.getPrenom()+" avec "+j1.getPoints()+" point(s)");
                vector2.add(j2.getNom()+" "+j2.getPrenom()+" avec "+j2.getPoints()+" point(s)");
            }       
        }else{
            
        }
        i+=1;
         model.addRow(vector1);
         model.addRow(vector2);
        System.out.println(vector1+" "+vector2);
            tabl.setModel(model);
            tabul.addTab("tour "+i,tabl);
            this.add(tabul);
    }//GEN-LAST:event_jouerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(int e=2;e<tabul.getComponentCount();){
            tabul.remove(e);
        }
        t = new Tournoi(dbinstence.all());
        i=0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void voirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirActionPerformed
        result();
    }//GEN-LAST:event_voirActionPerformed

    private void inidataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inidataActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Etes vous sure de la suppression?")==0){
            dbinstence.intDB();
            for(int e=2;e<tabul.getComponentCount();){
            tabul.remove(e);
        }
        t = new Tournoi(dbinstence.all());
        i=0;
        }
        attrpoint.setEnabled(true);
        infoattp.setText("---------Patientez SVP-------Les points Attribue Vous sera donne--------");
    }//GEN-LAST:event_inidataActionPerformed

    private void attrpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrpointActionPerformed
        try {
            attribuer();
            attrpoint.setEnabled(false);
        } catch (TournoiNonFiniException ex) {
            Logger.getLogger(TournoiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attrpointActionPerformed
    
    private void attribuer() throws TournoiNonFiniException{
        federation.attribuePoints(t);
        infoattp.setText("Le Gagnant a finalement: "+t.getVainqueur().getPoints()+" point(s)");
    }
    
    private void result(){
        if(!t.isFini()){
            JOptionPane.showMessageDialog(this, "Esperez pour un instant");
        }
        if(t!=null && t.isFini())
        try {
            gagnant.setText(t.getVainqueur().getNom()+" Est Gagant avec "+t.getVainqueur().getPoints()+" Point(s)");
            perdant.setText(t.getVaincu().getNom()+" Est Perdant avec "+t.getVaincu().getPoints()+" Point(s)");
        } catch (TournoiNonFiniException ex) {
            JOptionPane.showMessageDialog(this, "Le Tournoi n'est pas fini");
            Logger.getLogger(TournoiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int i=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attrpoint;
    private javax.swing.JLabel gagnant;
    private javax.swing.JLabel infoattp;
    private javax.swing.JButton inidata;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jouer;
    private javax.swing.JPanel option;
    private javax.swing.JLabel perdant;
    private javax.swing.JTabbedPane tabul;
    private javax.swing.JButton voir;
    // End of variables declaration//GEN-END:variables
}
